amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    laser_min_range: 0.1
    laser_max_range: 12.0
