# GLOBAL costmap parameters
global_frame: map
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 0.5
static_map: true

# Obstacle Layer
plugins:
  - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

inflation_layer:
  inflation_radius: 0.55
