slam_toolbox:
  ros__parameters:

    use_message_timestamps: true
    transform_timeout: 1.0

    # Grundlegende Konfiguration
    solver_plugin: "solver_plugins::CeresSolver"
    use_sim_time: false
    mode: "mapping"

    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"

    # Fusion
    use_scan_matching: true
    use_scan_barycenter: true
    use_odometry: true

    # Queue/Timing
    scan_queue_size: 100
    tf_buffer_duration: 10.0   # optional aber sinnvoll

    # Update-Trigger
    linear_update_distance: 0.05
    angular_update_distance: 0.05
    map_update_interval: 1.0

    # Sensor
    max_laser_range: 12.0
    min_laser_range: 0.2

    # Scan-matching tolerance
    minimum_score_threshold: 0.0
